CREATE TABLE [dbo].[DonorList]
(
	[pk_DonorList] NVARCHAR(15) NOT NULL PRIMARY KEY,
	[DonorType] VARCHAR(50) NULL,
    [AccountType] NVARCHAR(15) NULL, 
    [KeyName] NVARCHAR(100) NULL, 
    [AccountID] NVARCHAR(50) NULL, 
    [InsideSal] NVARCHAR(100) NULL, 
    [OutSideSal] NVARCHAR(100) NULL, 
    [HHOutsideSal] NVARCHAR(100) NULL, 
    [AccountName] NVARCHAR(100) NULL, 
    [AddressLine1] NVARCHAR(100) NULL, 
    [AddressLine2] NVARCHAR(100) NULL,
	[AddressLine3] [nvarchar](100) NULL,
	[AddressLine4] [nvarchar](100) NULL,
	[AddressLine5] [nvarchar](100) NULL,
	[City] [nvarchar](50) NULL,
	[State] [char](2) NULL,
	[PostCode] [nvarchar](15) NULL,
	[CountryIDTrans] [nvarchar](50) NULL,
	[StateDescription] [nvarchar](50) NULL,
	[EmailAddress] [nvarchar](100) NULL,
	[PhoneNumber] [nvarchar](25) NULL,
	[SPLCLeadCouncil] [bit] NULL,
	[MembershipYear] [int] NULL,
	[YearsSince] [int] NULL,
	[HPC] [money] NULL,
	[LastPaymentDate] [date] NULL,
	[LastPaymentAmount] [money] NULL,
	[SourceCode] [nvarchar](50) NULL
)
