CREATE TABLE [dbo].[EventList]
(
	[pk_Event] INT NOT NULL PRIMARY KEY IDENTITY, 
    [Date_Added] DATETIME2 NULL DEFAULT getdate(), 
    [User_Added] NVARCHAR(50) NULL,
	[EventName] NVARCHAR(100),
	[DisplayName] VARCHAR(50),
	[Speaker] VARCHAR(100) NULL,
	[TicketsAllowed] int DEFAULT 0,
    [Active] BIT NULL DEFAULT 0,
    [StartDate] DATETIME2 NULL, 
    [EndDate] DATETIME2 NULL, 
    [DoorsOpenDate] DATETIME2 NULL,
	[OnlineCloseDate] DATETIME2 NULL,
    [VenueName] NVARCHAR(50) NULL,
	[VenueAddress] VARCHAR(50) NULL,
    [VenueCity] NVARCHAR(50) NULL, 
    [VenueState] CHAR(2) NULL,
	[VenueZipCode] VARCHAR(10) NULL,
	[VenueComments] VARCHAR(255) NULL,
    [Capacity] INT NULL DEFAULT 0, 
    [ImageURL] NVARCHAR(MAX) NULL, 
    [InActive_Date] DATETIME2 NULL, 
    [InActive_User] NVARCHAR(50) NULL, 
    [HTML_Header] VARCHAR(MAX) NULL, 
    [HTML_FAQ] VARCHAR(MAX) NULL, 
    [Header_Image] IMAGE NULL, 
    [HTML_Yes] VARCHAR(MAX) NULL, 
    [HTML_No] VARCHAR(MAX) NULL, 
    [HTML_Wait] VARCHAR(MAX) NULL 
)
